### ISSUE TITLE
Authentication via a JavaScript client without CLIENT_SECRET ?

### ISSUE THREAD

**Issue by EugeneLiang** [authlib/example-oauth2-server#17]
Hi good day, 

thank you for releasing this example, really appreciate it. 

I've went through a few times on how to get this working and i got it to work.

So i have a question:
Is it possible to do a JavaScript client authentication with just the CLIENT_ID only ?

Cos currently, we need CLIENT_SECRET and CLIENT_ID in order to authenticate with app.py.
Is there anyway we can customize app.py such that we can authenticate with just CLIENT_ID only ?
( if app.py can accept CLIENT_ID only, than a JAvaScript client will be able to authenticate with app.py using CLIENT_ID only ).

Thanks!

**Comment by lepture** [comment]
the example is updated to [Authlib](https://authlib.org/)
