### ISSUE TITLE
Fail to generate authorization code

### ISSUE THREAD

**Issue by dark-reiser** [authlib/example-oauth2-server#35]
I executed this on terminal or using postman :
`curl -XPOST http://127.0.0.1:5000/oauth/authorize -F response_type=code -F client_id=QSgVk2cVtqI6qOpZv9pyCjVU -F redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Foauth%2Fauthorize`

but the response always:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```
because i need to get the code, to get access_token with grant_type=authorization_code

**Comment by lepture** [comment]
Yes, it will fail. You need to open the authorize page with browser, and click the confirm button in browser. The authorization_code flow requires a user action.

The error is caused by https://github.com/authlib/example-oauth2-server/blob/master/website/routes.py#L76

**Comment by lepture** [comment]
Authorization Code Flow is 3-legged authorization. You can try with Resource Owner Password Credentials Flow, which means `grant_type=password`.

**Comment by dark-reiser** [comment]
ah I see, thank you for the answer, :smile:
