### ISSUE TITLE
Insecure transport error Auth 2

### ISSUE THREAD

**Issue by Sphinxs** [authlib/example-oauth2-server#38]
I'm trying to use the api this way :

```python3
from authlib.client import OAuth2Session

session = OAuth2Session(client_id='example', scope=scope'test')

uri, state = session.authorization_url(url='http://127.0.0.1:5000/oauth/authorize', response_type='token')

urlencoded = str(set(uri) | set('=&;%+~,*'))

session.fetch_access_token(uri) # urlencoded
```

But I receive this error : 

`authlib.specs.rfc6749.errors.InsecureTransportError: insecure_transport:`

No matter if I'm passing the `uri` or the `url encoded` the error continues.

**Obs** : I did set the insecure transport to true ! ( `export OAUTHLIB_INSECURE_TRANSPORT=1`)

**Obs ²** : [Here](http://pydoc.net/Authlib/0.3/authlib.specs.rfc6749.errors/) I found the explanation to the error code, but if I really need a ssl to run it locally, how can I do this ?!

**Obs ³** : I tried with curl, and I'm using virtualenv ambient with [normal user](https://i.imgur.com/Oxpb3wF.png)

**Comment by sw-devendra** [comment]
How are you running the example? Are you running with sudo?
If yes, please try to drop sudo or use "sudo -E ...."

I struggled with the similar issue almost last week.

**Comment by sw-devendra** [comment]
Link to the issue I faced => https://github.com/authlib/example-oauth2-server/issues/37

**Comment by Sphinxs** [comment]
@sw-devendra I'm running like this : `source venv/bin/activate` and than `python api.py`

**Comment by lepture** [comment]
Try to print your environ in your code to check if the env has passed to python interpreter.

```python
import os

print(os.getenv('OAUTHLIB_INSECURE_TRANSPORT')
```

**Comment by Sphinxs** [comment]
The output for `print(os.getenv('OAUTHLIB_INSECURE_TRANSPORT')` was `None`, then I tried to set it in runtime `os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'` and now the output is `1`, but the issue continues :

```python
Traceback (most recent call last):
  File "api.py", line 37, in <module>
    session.fetch_access_token(urlencoded)
  File "venv/lib/python3.6/site-packages/authlib/client/oauth2_session.py", line 159, in fetch_a
ccess_token
    InsecureTransportError.check(url)
  File "venv/lib/python3.6/site-packages/authlib/specs/rfc6749/errors.py", line 92, in check
    raise cls()
authlib.specs.rfc6749.errors.InsecureTransportError: insecure_transport:
```

**Comment by lepture** [comment]
Oh. I just found that the env name is incorrect. There is no O, just authlib.

**Comment by Sphinxs** [comment]
I am registering the user, logging in, creating a client, authorizing it and then using the resources. I checked every step, but the authentication doesn't work.

I tried to set the insecure transport to true by terminal and at runtime (`export OAUTH ...` + `export AUTH ...`) and then authenticate by browser, by [script](https://github.com/authlib/example-oauth2-server/issues/38#issue-338403638) and by curl, nothing worked. I also tried to run as root.

If I try to authenticate by :

Browser or curl I receive `insecure_transport`

Script, passing the uri as parameter (`session.fetch_access_token`) I receive :

```python
Traceback (most recent call last):
  ...
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Script, passing the urlencoded as parameter (`session.fetch_access_token`) I receive :

```python
Traceback (most recent call last):
  ...
  File "venv/lib/python3.6/site-packages/requests/sessions.py", line 707, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'NeDYa+rp.ncyu3ObPxGfQB;Z7=_ht/jsiVU,&%2?gqd5o:C*J81l~0mzk'
```

**Comment by lepture** [comment]
Please ask your question on Stackoverflow instead with the full error stacks.
