### ISSUE TITLE
Which user id and password  should be used to revoke a token?

### ISSUE THREAD

**Issue by sw-devendra** [authlib/example-oauth2-server#39]
I am trying to revoke a token and server asks user name and password.

I have tried to use everything I could think,

1) user name: Client id
password: valid

2) uid: Client id
password: none (just enter)

3) client_id and client_secret in body

4) passing client_id:client_secret with url as mentioned in the example at https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication 
   example: https://username:password@www.example.com/

Every time I get an invalid client error (with curl) or request to authenticate (with a browser)

**Comment by hsethi2709** [comment]
What was the solution to this? What is the format for the curl command for token revocation?
