### ISSUE TITLE
working with multiple scopes?

### ISSUE THREAD

**Issue by valintepes** [authlib/example-oauth2-server#42]
How do we do that?  Do we enter it as a list in someway?

Specifically I am trying to reconfigure the example for OIDC, and I am trying to use scopes "openid" and "offline-access".  But when I try to do a authorization request with an appauth-android test app, the multiple scope always breaks with a invalid character (a space between the scopes).  A look at the "environ" parameter in flask/app.py showed that werkzeug.request has the query sort-of decoded, so the %20 of the space is just a " ".  This breaks in authlib/common/urls.py url_decode.

the appauth_android test app has worked against other oidc backends, so I don't think its mis-encoding the scope header.  I am unsure as to how to properly fix this though.

Anyway, if I write it as "scopeA+scopeB", I get past the error above, but then when it comes to validate the requested scopes, I get invalid scope when the string "scopeA+scopeB" is treated as one single scope, and doesn't match anything.

if I just use ONE scope it seems fine.  Gets past the scope check (and into other errors :-p).

**Comment by lepture** [comment]
I don't understand your question. Could you provide a minimal example to explain it.

**Comment by lepture** [comment]
Authlib 0.10 support scope operator now: https://docs.authlib.org/en/latest/flask/2/resource-server.html#flask-oauth2-multiple-scopes
