### ISSUE TITLE
Access Authorize Endpoint

### ISSUE THREAD

**Issue by imamdigmi** [authlib/example-oauth2-server#43]
I've following the tutorial, but i dont understand how to access `/oauth/authorize` endpoint, what parameters do I need to access the endpoint? because i got `invalid_grant` error response.
thanks!

**Comment by imamdigmi** [comment]
Solved.. i've read [the docs](https://docs.authlib.org/en/latest/specs/rfc6749.html#authlib.specs.rfc6749.grants.ImplicitGrant.validate_authorization_request) and got the answer.

**Comment by ma2ma** [comment]
I hava same problem. what is the answer?  thanks

**Comment by sunnysid3up** [comment]
@ma2ma Try this.
`http://0.0.0.0:5000/oauth/authorize?response_type=code&client_id=<client_id_here>`
