### ISSUE TITLE
Error following README: flask initdb command results in "no such command" error

### ISSUE THREAD

**Issue by shimniok** [authlib/example-oauth2-server#56]
To recreate on Linux Mint 18:

1. git clone https://github.com/authlib/example-oauth2-server.git
2. cd example-oauth2-server
3. virtualenv env
4. source env/bin/activate
5. pip install -r requirements.txt
6. export AUTHLIB_INSECURE_TRANSPORT=1 
_**NOTE:** the comment in README says to "Set Flask and Authlib environment variables:" but only provides one command show in #6._
7. flask initdb

The output from #7 is as follows:
```
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try "flask --help" for help.

Error: No such command "initdb".
```

**Comment by lepture** [comment]
Need to update readme. You don't need to type `initdb` command anymore due to https://github.com/authlib/example-oauth2-server/pull/53
