### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by Fizmath** [authlib/example-oauth2-server#64]
Hello

I followed the steps : after
`curl -u "xxxx...":"xxxx..."  -XPOST http://0.0.0.0:8080/oauth/token  -F grant_type=password -F username="me" -F password=valid -F scope=profile
`

i got the response in Ubuntu terminal : 

`{"access_token": "xxxx..", "expires_in": 864000, \
 "refresh_token": "xxxx..", "scope": "profile", "token_type": "Bearer"}`

 how to `curl` the  refresh_token ?  should we include something here ? : 

![include](https://user-images.githubusercontent.com/40030502/75149700-b0c64380-5713-11ea-80ac-fcadc4942fdb.png)

I wish there would be a complete example 

Thanks

**Comment by ZTAP0011** [comment]
Hello @Fizmath , how to use it with grant type authorization code?

**Comment by lepture** [comment]
You need to add `refresh_token` grant type here. Then curl with `-F grant_type=refresh_token`

**Comment by ZTAP0011** [comment]
Hello @lepture , I have one query in the above discussion first time when I make a request to -XPOST http://0.0.0.0:8080/oauth/token by passing the oauth code, at that time I only get access_token in response but not the request token.
