### ISSUE TITLE
Token Endpoint Auth Method

### ISSUE THREAD

**Issue by imanebosch** [authlib/example-oauth2-server#67]
When selecting `Token Endpoint Auth Method="none"` a client secret is still issued. According to the documentation `none`means that the client is public and has no secret. 

Once the issue is solved,

Endpoint 

`@bp.route('/oauth/token', methods=['POST'])
def issue_token():
    return authorization.create_token_response()`

does not work with grant `password`. But If I pass within the body `client_id` it works. However, according to [RFC6749](https://tools.ietf.org/html/rfc6749#section-4.3) the body should only contain `grant_type`, `username`, `password` and `scope` 

I might have missed something...
Btw, Should I public client have its own id?

**Comment by lepture** [comment]
I've fixed the bug. Thanks for your feedback.
