### ISSUE TITLE
Use client_secret_post as auth method

### ISSUE THREAD

**Issue by TheStaticTurtle** [authlib/example-oauth2-server#68]
Hey I'm trying to use client_secret_post to auth and get my token
`curl -XPOST xxxxxxxxxxxxxx -F grant_type=password -F username=test -F password=valid -F scope=profile -F client_id=xxxxxxxxx -F client_secret=xxxxxxxxx`

Just returns `{"error": "invalid_client"}` any idea ?

**Comment by lepture** [comment]
This is the default token endpoint auth methods:

```
TOKEN_ENDPOINT_AUTH_METHODS = ['client_secret_basic']
```

You need to customize password grant with:

```
TOKEN_ENDPOINT_AUTH_METHODS = ['client_secret_basic', 'client_secret_post']
```

**Comment by TheStaticTurtle** [comment]
You mean in the AuthorizationCodeGrant class ? because it already is from the exampleI've got:

```
    TOKEN_ENDPOINT_AUTH_METHODS = [
        'client_secret_basic',
        'client_secret_post',
        'none',
    ]
```

**Comment by lepture** [comment]
You are using `password` grant, which means you need to customize `PasswordGrant` class.
